dbt_project:
  outputs:
    dev:
      account: *********
      database: dataset
      password: *******
      role: accountadmin
      schema: *******
      threads: 4
      type: snowflake
      user: *******
      warehouse: compute_wh
  target: dev
